apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-sa
  namespace: ota-pipeline
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: campaign-sa
  namespace: ota-pipeline
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: package-sa
  namespace: ota-pipeline
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: deploy-sa
  namespace: ota-pipeline
